version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: docker.io/postgres:13
    environment:
      POSTGRES_DB: db_fatec_dsm
      POSTGRES_USER: fatec
      POSTGRES_PASSWORD: fatec777
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: 
